---
version: "3"

networks:
  loki:
x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: "100m"
    max-file: "5"

x-resources:
  &default-resources
  cpus: 0.5
  mem_limit: 200M

x-custom:
  &common
  logging: *default-logging
  restart: unless-stopped
  networks:
    - loki
  <<: *default-resources

volumes:
  loki-data:
  promtail-data:
  grafana-data:
  prometheus-data:

services:
  app_python:
    image: path242/clock:latest
    ports:
      - 5000:8000
    <<: *common

  promtail:
      image: grafana/promtail:2.3.0
      volumes:
        - /var/log:/var/log
        - ./promtail.yaml:/etc/promtail/config.yaml
        - promtail-data:/var/lib/promtail/positions
      command: -config.file=/etc/promtail/config.yaml
      <<: *common

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    <<: *common
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    <<: *common
  prometheus:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"
    <<: *common