apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-app
  labels:
    app: clock-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clock-app
  template:
    metadata:
      labels:
        app: clock-app
    spec:
      containers:
      - name: clock-app
        image: path242/clock:latest
        ports:
        - containerPort: 8000
