# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "lab1" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Dockerize
        run: |
              echo "${{ secrets.DOCKERPW }}" | docker login -u "path242" --password-stdin
              docker image build -t path242/clockApp:latest .
              docker push path242/clockApp:latest
