# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "lab1", "lab2" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            context: ./app_python
            push: true
            tags: ${{ secrets.DOCKERUSER }}/clock:latest